### ISSUE TITLE
Other issues using CiviCRM & Domain Access?

### ISSUE THREAD

**Issue by JoeMurray** [PalanteJon/domain_civicrm#1]
Thanks for this module, Jon. Are there outstanding feature requests / other needed or useful functionality that you can think of when running CiviCRM and Domain Access? We're considering pros/cons of Drupal Domain Access vs multisite and leaning towards Domain Access.

**Comment by MegaphoneJon** [comment]
Not really!  I put notes on wiki.c.o on the multi-site setup page on how to set up with Domain Access - essentially, you need to put a case switch statement in civicrm.settings.php, which is similar to Wordpress multi-site.  I've never run Civi multisite on Drupal multisite, just Domain Access, so I can't compare it - but it works pretty well.  Even this module handles a bit of an edge case.  The wiki docs are messy, but everything should be there; if not, feel free to contact me by e-mail.

**Comment by JoeMurray** [comment]
Thanks, Jon. For other's reference, see http://wiki.civicrm.org/confluence/display/CRMDOC/Multi+Site+Installation#MultiSiteInstallation-D.DrupalwiththeDomainAccessmodule.

**Comment by MegaphoneJon** [comment]
I'll also put out there that I had a multi-site mixup today because I
didn't follow my own examples from here:
https://hq.palantetech.coop/projects/commons/wiki/CiviCRM_multi-site_checklist

In particular, I didn't set my userFrameworkResourceURL overrides in
civicrm.settings.php on a per-domain basis - this breaks KCFinder, and
probably more.
